apiVersion: apps/v1
kind: Deployment
metadata:
  name: be-deployment
  namespace: tmbackend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: tmbackend
        image: prashantdey/tmbeb9:v1.0
        ports:
        - containerPort: 3001
        env:
        - name: PORT
          value: "3001"
        - name: MONGO_URI
          valueFrom:
            secretKeyRef:
              name: be-secret
              key: MONGO_URI          
